### ISSUE TITLE
not found utils.py in reporsitory

### ISSUE THREAD

**Issue by koke2c95** [GFNOrg/gfn-lm-tuning#1]
[rng notebook](https://github.com/GFNOrg/gfn-lm-tuning/blob/main/rng/notebooks/RNG_GFN.ipynb)

```from utils import generate, generate_and_return_eos_logprob```

need utils.py for running rng demo. also can you attach these peft ckpt (rng, arithmetic, infilling, next sentence) ? thanks

**Comment by MJ10** [comment]
Hi, thanks for letting us know! You can use the `utils.py` from `infill_subj_arithmetic`. We'll update the repo to fix this discrepancy. 

Here is the checkpoint of the fine-tuned model used as the base model for the story infilling experiments: https://drive.google.com/drive/folders/1eJibT9MPoJ1YtAOJ99QTvDQGlyc3m59H?usp=sharing

**Comment by youqad** [comment]
Thanks @koke2c95 for letting us know about the import problem, sorry for the inconvenience, it should be fixed now. 
Regarding the checkpoint weights, sure, I'll upload the rng ones on Google Drive or HuggingFace soon and add the links to the rng README.
